package doctorappointment.doctoravailability.Entity;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.UUID;

@Document(collection = "slots") // Maps this class to the "slots" collection in MongoDB
public class Slot {

    @Id // Marks this field as the primary key (auto-generated by MongoDB)
    private String id; // Changed to String to support MongoDB's ObjectId

    @CreatedDate // Automatically sets this field to the current date and time when the entity is created
    private LocalDateTime time;

    private String doctorName;
    private boolean isReserved;
    private double cost;

    // Default constructor (required by Spring Data MongoDB)
    public Slot() {
    }

    // Parameterized constructor (without id and time)
    public Slot(String doctorName, boolean isReserved, double cost) {
        this.doctorName = doctorName;
        this.isReserved = isReserved;
        this.cost = cost;
    }

    // Getters and setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public boolean isReserved() {
        return isReserved;
    }

    public void setReserved(boolean reserved) {
        isReserved = reserved;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    @Override
    public String toString() {
        return "Slot{" +
                "id='" + id + '\'' +
                ", time=" + time +
                ", doctorName='" + doctorName + '\'' +
                ", isReserved=" + isReserved +
                ", cost=" + cost +
                '}';
    }
}